/* ===================================================================
   build-lingo.mjs
   -------------------------------------------------------------------
   Generates the Learn the Lingo glossary pages from lingo-content.mjs
   and rewrites the A-Z index on learn-the-lingo.html to match.

   RUN:  node tools/build-lingo.mjs
         node tools/build-lingo.mjs --check   (writes nothing, exits 1
                                               if a page is out of date)

   WHY A GENERATOR
   Same reason build-calculators.mjs exists. Every term page carries the
   same head, the same JSON-LD @graph, the same nav, the same rail and
   the same disclaimer. Hand-maintaining that across nine files is how
   one page ends up with a canonical pointing at the wrong URL and a
   FAQPage block that disagrees with the visible FAQ.

   WHAT IT DOES NOT DO
   Footers - tools/stamp-footers.mjs owns those and must run after this.
   The template emits FOOTER:START/END empty and the stamper fills them.
   The nav block is read from nav.template.html so it comes out already
   stamped and stamp-nav.mjs --check passes with no extra step; if those
   two ever drift, every glossary page fails the nav gate at once.

   ORDER: build-lingo -> stamp-footers -> update sitemap if a term is new.
   =================================================================== */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { TERMS, REVIEWED } from './lingo-content.mjs';
import { navFor, GROUPS, termsInGroup } from './nav-template.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://hustlin.org';
const DIR = 'learn-the-lingo';
const CHECK = process.argv.includes('--check');
/* --fresh ignores the existing file entirely: no footer carry-forward, no
   up-to-date skip. Use it after a template change that left a page malformed,
   then run stamp-footers.mjs. */
const FRESH = process.argv.includes('--fresh');
const R = (p) => readFileSync(join(ROOT, p), 'utf8');

/* stamp-footers.mjs finds its block by an EXACT marker string that carries a
   "generated by" note inside the comment. Emitting the bare <!-- FOOTER:START -->
   pair instead meant the stamper could not find a block to fill, appended its own
   before </body>, and the next rebuild's carry-forward duplicated it — three
   markers and two footers on every page. The tripwire below fails the build
   loudly if that string ever changes in stamp-footers.mjs, rather than letting
   it drift and reproduce the same mess. */
const FOOTER_START = '<!-- FOOTER:START — generated by tools/stamp-footers.mjs from footer.template.html. DO NOT EDIT BY HAND. -->';
const FOOTER_END = '<!-- FOOTER:END -->';
if (!R('tools/stamp-footers.mjs').includes(FOOTER_START)) {
  throw new Error('FOOTER_START no longer matches the marker in tools/stamp-footers.mjs — update build-lingo.mjs');
}

/* Depth 1: every glossary page sits in learn-the-lingo/. navFor() applies the
   same transform stamp-nav.mjs does, from the same module, so these pages come
   out already stamped and the nav gate passes with no extra step. */
const NAV_BLOCK = '<!-- NAV:START -->\n' + navFor(1) + '\n<!-- NAV:END -->';

const BY_SLUG = Object.fromEntries(TERMS.map((t) => [t.slug, t]));
const jstr = (s) => JSON.stringify(String(s));

/* The visible FAQ and the FAQPage block are written from ONE array, so they
   cannot disagree. Google treats a mismatch as a structured-data violation
   and it is the single easiest way for a hand-maintained page to go wrong. */
const faqJsonLd = (t) => t.faq.map((f) => `        {
          "@type": "Question",
          "name": ${jstr(f.q)},
          "acceptedAnswer": { "@type": "Answer", "text": ${jstr(f.a)} }
        }`).join(',\n');

const relCard = (r) => {
  const target = BY_SLUG[r.slug];
  if (!target) throw new Error(`related term "${r.slug}" is not in TERMS`);
  return `      <a href="${r.slug}.html"><b>${r.label}</b><span>${r.blurb}</span></a>`;
};

/* t.tool.lbl is optional and defaults to "Run the numbers".
   The trading and markets terms added 2026-08-12 point their rail card at a live
   Markets pillar rather than a calculator - the site has no technical-analysis
   calculator - and "Run the numbers" over a link to a chart is the wrong promise.
   Omitting lbl reproduces the previous output byte for byte, which is why the
   twenty-eight existing terms did not need touching. */
function page(t) {
  const url = `${SITE}/${DIR}/${t.slug}.html`;
  const h1 = t.h1span ? `${t.h1} <span>${t.h1span}</span>` : t.h1;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${t.title}</title>
<meta name="description" content="${t.metaDesc}">
<link rel="canonical" href="${url}">
<meta property="og:type" content="article">
<meta property="og:url" content="${url}">
<meta property="og:title" content="${t.ogTitle}">
<meta property="og:description" content="${t.ogDesc}">
<meta property="og:image" content="${SITE}/assets/social-preview.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${t.ogTitle}">
<meta name="twitter:description" content="${t.ogDesc}">
<meta name="twitter:image" content="${SITE}/assets/social-preview.png">

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "DefinedTerm",
      "@id": "${url}#term",
      "name": ${jstr(t.h1span ? `${t.term} (${t.shortName})` : t.term)},
      "alternateName": ${JSON.stringify(t.alternateName)},
      "description": ${jstr(t.termDescription)},
      "url": "${url}",
      "inDefinedTermSet": { "@id": "${SITE}/learn-the-lingo.html#glossary" }
    },
    {
      "@type": "DefinedTermSet",
      "@id": "${SITE}/learn-the-lingo.html#glossary",
      "name": "Learn the Lingo",
      "description": "A plain-language dictionary of money, credit, investing and market terms, written for people building from the ground up.",
      "url": "${SITE}/learn-the-lingo.html"
    },
    {
      "@type": "Article",
      "headline": ${jstr(t.articleHeadline)},
      "description": ${jstr(t.articleDescription)},
      "url": "${url}",
      "image": "${SITE}/assets/social-preview.png",
      "datePublished": "2026-08-11", "dateModified": "2026-08-11",
      "inLanguage": "en-US", "isAccessibleForFree": true,
      "about": { "@id": "${url}#term" },
      "author": { "@id": "${SITE}/#organization" },
      "publisher": { "@id": "${SITE}/#organization" },
      "mainEntityOfPage": "${url}"
    },
    {
      "@type": "Organization", "@id": "${SITE}/#organization",
      "name": "Hustlin'", "url": "${SITE}/",
      "logo": { "@type": "ImageObject", "url": "${SITE}/assets/hustlin-logo.png" },
      "publishingPrinciples": "${SITE}/about.html"
    },
    {
      "@type": "BreadcrumbList",
      "itemListElement": [
        { "@type": "ListItem", "position": 1, "name": "Hustlin'", "item": "${SITE}/" },
        { "@type": "ListItem", "position": 2, "name": "Learn the Lingo", "item": "${SITE}/learn-the-lingo.html" },
        { "@type": "ListItem", "position": 3, "name": ${jstr(t.shortName)}, "item": "${url}" }
      ]
    },
    {
      "@type": "FAQPage",
      "mainEntity": [
${faqJsonLd(t)}
      ]
    }
  ]
}
</script>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../styles.css?v=DEPLOYSTAMP">
<link rel="stylesheet" href="lingo.css?v=DEPLOYSTAMP">
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1249156793457835"
     crossorigin="anonymous"></script>
</head>
<body>

${NAV_BLOCK}

<section class="hero gls-hero">
  <div class="hero-wrap">
    <div>
      <div class="breadcrumb">
        <a href="../index.html">Hustlin'</a>
        <span class="breadcrumb-sep">/</span>
        <a href="../learn-the-lingo.html">Learn the Lingo</a>
        <span class="breadcrumb-sep">/</span>
        <span>${t.shortName}</span>
      </div>
      <div class="eyebrow"><span>&#9679;</span> ${t.eyebrow}</div>
      <h1 class="hero-h1">${h1}</h1>
      <p class="hero-sub">${t.heroSub}</p>
      <p class="gls-aka"><b>Also called:</b> ${t.aka}</p>
    </div>
  </div>
</section>

<div class="gls-shell">

<article class="gls-body">

  <p class="gls-rev"><b>Reviewed ${t.reviewed || REVIEWED}</b> &middot; Sourced from ${t.sourcedFrom}</p>

  <div class="gls-def">
    <span class="gls-lbl">The short version</span>
${t.shortVersion.map((p) => `    <p>${p}</p>`).join('\n')}
  </div>

  <div class="gls-key">
    <span class="gls-lbl">Key takeaways</span>
    <ul>
${t.keyTakeaways.map((li) => `      <li>${li}</li>`).join('\n')}
    </ul>
  </div>

${t.sections.map((s) => `  <h2 id="${s.id}">${s.h2}</h2>\n\n  ${s.html}`).join('\n\n')}

  <section class="gls-faq">
    <h2 id="faq">Frequently asked questions</h2>

${t.faq.map((f) => `    <h3>${f.q}</h3>\n    <p>${f.a}</p>`).join('\n\n')}
  </section>

  <section class="gls-rel">
    <h2>Related terms</h2>
    <div class="gls-rel-grid">
${t.related.map(relCard).join('\n')}
    </div>
  </section>

  <section class="gls-next">
    <h2>Where to go next</h2>
    <ul>
${t.next.map((li) => `      ${li}`).join('\n')}
    </ul>
  </section>

  <section class="gls-src">
    <span class="gls-lbl">Sources</span>
    <ol>
${t.sources.map((li) => `      ${li}`).join('\n')}
    </ol>
  </section>

  <p class="gls-disc">The figures on this page are checked against the source that publishes them, and dated. Published rates move after the release named above &mdash; the linked source always carries the current number. This page explains a term; it does not recommend a product.</p>

</article>

<aside class="gls-rail">
  <nav class="gls-toc" aria-label="On this page">
    <span class="gls-lbl">On this page</span>
    <ol>
${t.toc.map((i) => `      <li><a href="${i.href}">${i.label}</a></li>`).join('\n')}
    </ol>
  </nav>

  <div class="gls-tool">
    <span class="gls-lbl">${t.tool.lbl || 'Run the numbers'}</span>
    <p>${t.tool.blurb}</p>
    <a class="gls-cta" href="${t.tool.href}">${t.tool.label} &rarr;</a>
  </div>
</aside>

</div>

${FOOTER_START}
${FOOTER_END}
</body>
</html>
`;
}

/* ---------- the hub's A-Z index ----------------------------------- */

const LETTERS = ['#', ...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('')];
// A term whose name starts with a digit files under '#'. The anchor id cannot be
// '#' itself (href="##" is not a link), so the '#' bucket anchors to id="num".
const anchorId = (L) => (L === '#' ? 'num' : L);

function indexBlocks() {
  const byLetter = new Map();
  for (const t of TERMS) {
    const label = t.shortName && t.shortName !== t.term ? `${t.shortName} (${t.term})` : t.term;
    if (!byLetter.has(t.letter)) byLetter.set(t.letter, []);
    byLetter.get(t.letter).push({ label, blurb: t.indexBlurb, slug: t.slug });
  }
  for (const rows of byLetter.values()) rows.sort((a, b) => a.label.localeCompare(b.label));

  const jump = LETTERS.map((L) =>
    byLetter.has(L) ? `    <a href="#${anchorId(L)}">${L}</a>` : `    <a class="is-empty" href="#${anchorId(L)}">${L}</a>`
  ).join('\n');

  const groups = LETTERS.filter((L) => byLetter.has(L)).map((L) => {
    const rows = byLetter.get(L)
      .map((r) => `      <a href="${DIR}/${r.slug}.html"><b>${r.label}</b><span>${r.blurb}</span></a>`)
      .join('\n');
    return `  <section class="gls-idx-group">\n    <h2 class="gls-idx-letter" id="${anchorId(L)}">${L}</h2>\n    <div class="gls-idx-rows">\n${rows}\n    </div>\n  </section>`;
  }).join('\n\n');

  return { jump, groups };
}

/* The hub's "Browse by topic" sections.
   -----------------------------------------------------------------------
   Generated from the SAME GROUPS array the nav panel is built from, so a
   nav tile can never point at an anchor that does not exist. The anchor
   ids are id="g-<key>", matching the hrefs in nav-template.mjs.

   These sections deliberately repeat terms that also appear in the A-Z
   index below them. Two ways in is the point: the nav sends topic
   browsers here, and someone who knows the word uses the letters. */
function topicBlocks() {
  return GROUPS.map((g) => {
    const rows = termsInGroup(g.key)
      .map((t) => {
        const label = t.shortName && t.shortName !== t.term ? `${t.shortName} (${t.term})` : t.term;
        return `      <a href="${DIR}/${t.slug}.html"><b>${label}</b><span>${t.indexBlurb}</span></a>`;
      })
      .join('\n');
    const n = termsInGroup(g.key).length;
    return `  <section class="gls-top-group" id="g-${g.key}">\n    <h3 class="gls-top-h">${g.label}<span>${n} terms</span></h3>\n    <div class="gls-idx-rows">\n${rows}\n    </div>\n  </section>`;
  }).join('\n\n');
}

function hub(html) {
  for (const mk of ['<!-- LINGO-INDEX:START', '<!-- LINGO-INDEX:END', '<!-- LINGO-TOPICS:START', '<!-- LINGO-TOPICS:END']) {
    if (!html.includes(mk)) throw new Error(`learn-the-lingo.html is missing ${mk} — the hub block markers are the only thing telling the builder where to write.`);
  }
  const { jump, groups } = indexBlocks();
  let out = html.replace(
    /(<nav class="gls-idx-jump" aria-label="Jump to letter">\n)[\s\S]*?(\n  <\/nav>)/,
    (m, a, b) => a + jump + b
  );
  /* Marker-anchored, not position-anchored. The old regex ran from the first
     .gls-idx-group to the first blank-line </div>, which only worked while the
     A-Z index was the LAST thing in .gls-idx. The index was moved above "Browse
     by topic" on 2026-08-15 and that regex would have swallowed the topic
     sections whole. Markers make the block order-independent, the same contract
     LINGO-TOPICS already had. */
  out = out.replace(
    /(  <!-- LINGO-INDEX:START[^>]*-->\n)[\s\S]*?(  <!-- LINGO-INDEX:END -->)/,
    (m, a, b) => a + groups + '\n' + b
  );
  /* Callback, not a string: the generated markup is full of dollar amounts
     and "$&" or "$1" in a replacement string would be read as a backreference. */
  out = out.replace(
    /(<!-- LINGO-TOPICS:START[^>]*-->\n)[\s\S]*?(  <!-- LINGO-TOPICS:END -->)/,
    (m, a, b) => a + topicBlocks() + '\n' + b
  );
  return out;
}

/* ---------- run --------------------------------------------------- */

let wrote = 0;
const stale = [];

for (const t of TERMS) {
  if (t.generated === false) continue;
  const rel = `${DIR}/${t.slug}.html`;
  const next = page(t);
  const prev = existsSync(join(ROOT, rel)) ? R(rel) : null;

  /* Compare with the cache-bust token normalised. The deploy rewrites ?v= at
     step 6, so a page that is byte-identical apart from its stamp is current,
     not drifted. Skipping this is how a --check gate learns to cry wolf after
     every single deploy. */
  const norm = (s) => (s === null ? null : s.replace(/\.(js|css)\?v=[^"']*/g, '.$1?v=X')
                                            .replace(/<!-- FOOTER:START[\s\S]*?FOOTER:END -->/, 'F'));
  if (!FRESH && norm(prev) === norm(next)) continue;

  if (CHECK) { stale.push(rel); continue; }

  /* Carry an existing stamped footer forward, exactly as build-calculators
     does, so a rebuild does not un-stamp every page and fail gate 2. */
  /* stamp-footers.mjs writes its own START marker with a "generated by" note in
     it, NOT the bare one this template emits. Matching only the bare marker made
     --check report all nine pages stale after every footer stamp — a gate that
     always fails is a gate you learn to ignore. */
  const keep = !FRESH && prev && /<!-- FOOTER:START[\s\S]*?FOOTER:END -->/.exec(prev);
  const body = keep ? next.replace(`${FOOTER_START}\n${FOOTER_END}`, keep[0]) : next;
  writeFileSync(join(ROOT, rel), body, 'utf8');
  wrote++;
  console.log(`  ${rel}`);
}

const hubPath = 'learn-the-lingo.html';
const hubPrev = R(hubPath);
const hubNext = hub(hubPrev);
if (hubPrev !== hubNext) {
  if (CHECK) stale.push(hubPath);
  else { writeFileSync(join(ROOT, hubPath), hubNext, 'utf8'); wrote++; console.log(`  ${hubPath} (A-Z index)`); }
}

const total = TERMS.filter((t) => t.generated !== false).length;
console.log(`\n${CHECK ? 'checked' : 'built'} ${total} generated term page(s) + the hub index` +
            (CHECK ? '' : `, ${wrote} file(s) written`));

if (CHECK && stale.length) {
  console.log('\nThese are out of date with lingo-content.mjs:');
  for (const s of stale) console.log(`  ${s}`);
  console.log('\nFix with:  node tools/build-lingo.mjs');
  process.exitCode = 1;
}
